### ISSUE TITLE
More generated schemas issues

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#100]
* google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_stable: 1 error occurred:
	* google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_stable: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:org_mozilla_vrbrowser_stable.session_end_v1. Field metrics.counter is missing in new schema, invalid

	* google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_live: 1 error occurred:
	* google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_live: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:org_mozilla_vrbrowser_live.session_end_v1. Field metrics.counter is missing in new schema, invalid

	* google_bigquery_table.org_mozilla_ios_lockbox_metrics_v1_stable: 1 error occurred:
	* google_bigquery_table.org_mozilla_ios_lockbox_metrics_v1_stable: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:org_mozilla_ios_lockbox_stable.metrics_v1. Field metrics.counter.glean_error_preinit_tasks_overflow is missing in new schema, invalid

	* google_bigquery_table.org_mozilla_ios_lockbox_metrics_v1_live: 1 error occurred:
	* google_bigquery_table.org_mozilla_ios_lockbox_metrics_v1_live: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:org_mozilla_ios_lockbox_live.metrics_v1. Field metrics.counter.glean_error_preinit_tasks_overflow is missing in new schema, invalid

It's possible these issues due to a bad rollout of broken schemas as initial schemas, but it looks like vbrowser has been around since November so this may be newly introduced. 

/CC @fbertsch

**Comment by fbertsch** [comment]
It looks to me like this is because of the cloudfront caching issue, [since the probes are in the probe-info-service](https://probeinfo.telemetry.mozilla.org/glean/glean/metrics?r=34583745934). Investigating.

**Comment by whd** [comment]
With the latest push only vbrowser remains an issue: 

	* google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_stable: 1 error occurred:
	* google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_stable: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:org_mozilla_vrbrowser_stable.session_end_v1. Field metrics.counter is missing in new schema, invalid


	* google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_live: 1 error occurred:
	* google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_live: googleapi: Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:org_mozilla_vrbrowser_live.session_end_v1. Field metrics.counter is missing in new schema, invalid

**Comment by fbertsch** [comment]
Oh my, another casualty of the kebab case

**Comment by fbertsch** [comment]
This PR never got merged: https://github.com/MozillaReality/FirefoxReality/pull/2478

**Comment by fbertsch** [comment]
Fixed with https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/9f4cfa18fdf2fac01a2e37cef38935151fb72cb5.
