### ISSUE TITLE
Add README to generated-schemas branch

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/mozilla-schema-generator#102]
The generated schemas branch should include a README so it is more approachable to users.

I think it would be useful to include some of the following information:

* A title
* Short summary about generating schemas
* A generated log of the last month of commits
* A generated directory hierarchy using `tree`

This can be generated and committed around here:

https://github.com/mozilla/mozilla-schema-generator/blob/36da4914f2694f46a5dee36f0b6fe27295e1f656/bin/schema_generator.sh#L118-L120

**Comment by wlach** [comment]
@JoyLubega want to give this a try? @acmiyaguchi has offered to mentor / review. I would probably start by looking at this repository (as well as probe scraper: https://github.com/mozilla/probe-scraper) to get an idea of how it's used and what it does. Feel free also to ask in #glean-dictionary if you have questions.

**Comment by JoyLubega** [comment]
Sure. Thanks. Let me start right away
