### ISSUE TITLE
Incorrectly claim there are 'metrics', 'baseline', and 'events' pings for python apps

### ISSUE THREAD

**Issue by wlach** [mozilla/mozilla-schema-generator#145]
The schema generator incorrectly infers that Glean python applications (like burnham or mozregression) have 'metrics', 'baseline', and 'events' pings because they are defined in `glean-core` (https://github.com/mozilla/glean/blob/ebeea9f8219d146b27dab0c255f3c8ff7143fad7/glean-core/pings.yaml) even though the documentation explicitly says those types of pings aren't sent from the python bindings e.g.:

https://mozilla.github.io/glean/book/user/pings/baseline.html

Here's the code reference where these ping types are erroneously picked up:

https://github.com/mozilla/mozilla-schema-generator/blob/6786e51b3fc4af77dd29661ffa12ed8adb870c3b/mozilla_schema_generator/glean_ping.py#L71

In reality, python apps should only claim to have the deletion ping by default (in addition to any pings their own applications define)

I don't claim this is an *urgent* problem, but my guess is that we'll encounter other issues shaped like this in the future as we further transition Glean away from being mobile-only e.g. with FoG.

/cc @hackebrot @mdboom @chutten

**Comment by fbertsch** [comment]
The resolution to this is three-fold:
1. Merge https://github.com/mozilla/probe-scraper/pull/217, and use the new `glean-core` as the default dependency. Existing Glean dependencies will need to be grandfathered in.
2. Have MSG load the `client_info` section, which currently contains android-specific pieces, and ensure those metrics are in e.g. `glean-android`.
3. (optional) Remove those android-specific fields from the views for the grandfathered-in views in (1.)

**Comment by wlach** [comment]
@fbertsch you implied this should be fixed by #158? Please close if so

**Comment by wlach** [comment]
I believe this is fixed now, though we haven't bothered updating the legacy applications.
