### ISSUE TITLE
Error 400: Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:telemetry_stable.saved_session_v4. Field payload.processes.content.scalars.printing_dialog_opened_via_preview_tm is missing in new schema, invalid

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#147]
/CC @fbertsch 

Looks like these [moved](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/8b081df1b626ac554301d669bf2c2f0eb028c1e7#diff-1778949213ca7cc325702ef64b3460f8) from content to parent.

**Comment by fbertsch** [comment]
Easiest fix might be to merge https://github.com/mozilla/mozilla-schema-generator/pull/144. cc @scholtzan, where are we on removal of saved-session? My guess is this error is related to that deprecation.

**Comment by scholtzan** [comment]
Just merged #144. Wasn't sure if I should wait for https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/533 before merging, but it's all good to go

**Comment by whd** [comment]
This affects all the main ping clones including main itself. Running MSG post #144 merge resulted in https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/d3844dfdc0ed692177815712f6608d6a2ac40afd which remove saved-session but it didn't change main other pings, so I would still expect this to fail when deployed to stage.
