### ISSUE TITLE
Add default option to generate-glean-pings command

### ISSUE THREAD

**Issue by DawoodShahat** [mozilla/mozilla-schema-generator#160]
When generating glean-ping-schemas for each app using the following command
```
mozilla-schema-generator generate-glean-pings
```

It throws this error
![Screenshot 2020-10-15 at 3 50 04 AM](https://user-images.githubusercontent.com/19612755/96163662-99062e80-0f33-11eb-98ff-43f1736ba2b3.png)

When this option ```--mps-branch master```  is specified it uses mozilla-pipeline-schemas' master branch  as a reference
to generate schemas from.  

Shouldn't it be the default option?

If it isn't need to be set the default option for some reason. I think we should update the README with this information.

**Comment by DawoodShahat** [comment]
Please do share your opinion on this @wlach @fbertsch whenever possible. Thanks!

**Comment by fbertsch** [comment]
Thanks for filing this, @DawoodShahat. @acmiyaguchi put in a fix.

**Comment by DawoodShahat** [comment]
I'm glad I could be of help.
