### ISSUE TITLE
Could we remove the need for glean.yaml?

### ISSUE THREAD

**Issue by mdboom** [mozilla/mozilla-schema-generator#183]
It seems that everything in `configs/glean.yaml` could be autogenerated from the keys of this object in the Glean JSON schema [here](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/master/schemas/glean/glean/glean.1.schema.json#L118).  If we did that, it would be one less thing to update when adding new metric types.

Is that a good idea, or are there good reasons to keep the `glean.yaml` file?

**Comment by jklukas** [comment]
There has so far been no priority to implement this, but I wrote up [a proposal for schema generation metadata](https://docs.google.com/document/d/1TGgJe_rHKNSz0nyB6Ayj6lFPdgsnZ7xZqe7T5hsEJiQ/edit) which would push this into the Glean JSON schema itself:

```
      ...
      "properties": {
        "boolean": {
          "mozInjectProbes": {
              # Metadata about what to inject goes here
          } 
          "additionalProperties": {
            "type": "boolean"
          },
          "propertyNames": {
            "maxLength": 61,
            "pattern": "^[a-z_][a-z0-9_]{0,29}(\\.[a-z_][a-z0-9_]{0,29})+$",
            "type": "string"
          },
          "type": "object"
        },
        ...
```

That would make things more explicit and remove the need for a separate configuration file.

**Comment by mdboom** [comment]
Oh, yeah, I even read that proposal, but hadn't connected the dots in my mind.

No real need to reprioritize anything at this point -- this just came up from writing docs [over here](https://github.com/mozilla/glean/pull/1537)

**Comment by fbertsch** [comment]
Adding new metric types is a rare enough occurrence that I don't think automating it is worth the additional risk. With @jklukas's proposal we would still be manually specifying those transformations, but at least it would be in a single PR. For now, it's probably best to keep things as they are. @mdboom is that okay with you?

**Comment by mdboom** [comment]
That works!  Thanks for the additional context.
