### ISSUE TITLE
crash_v4: googleapi: Error 400: The description for field quota_manager_shutdown_timeout is too long. The maximum length is 1024 characters., invalid

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#188]
[This line](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/674d30a4a62827a3aa86c7938d1573550d886e00#diff-e7253604f994d029e444b2b3de755395a0791215739b4a524a58bf0a8fc5ee55R1462) is too long for a BQ schema field description. I'm filing this in MSG since I think it's probably fine to support longer descriptions than that and truncate only in the BQ schema. I thought we were doing this via https://github.com/mozilla/mozilla-schema-generator/pull/114 but that's probably only for probes picked up via probe-scraper.

/CC @acmiyaguchi @scholtzan as people around this week that are likely to have opinions on where to handle this. This failed on deploy to stage but should probably have failed before then.

**Comment by scholtzan** [comment]
This is probably something the jsonschema-transpiler should handle. I can open a PR
