### ISSUE TITLE
Missing glean metadata propagation for firefox-desktop/pageload

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#264]
https://github.com/mozilla/probe-scraper/pull/537

Retention metadata is [set to 120 days](https://github.com/mozilla/probe-scraper/blob/main/repositories.yaml#L334-L351) in probe-scraper but that [metadata doesn't wind up in the generated MPS branch](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/generated-schemas/schemas/firefox-desktop/pageload/pageload.1.schema.json#L10). I checked history and it was never added in the first place.

This is pretty strange, as metadata for all other doctypes that have specific `moz_pipeline_metadata`  appear to propagate correctly. For instance: [spoc](https://github.com/mozilla/probe-scraper/blob/main/repositories.yaml#L465)  looks like essentially the exact same config and [propagates correctly](https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/generated-schemas/schemas/org-mozilla-fenix/spoc/spoc.1.schema.json#L11).

**Comment by whd** [comment]
Actual rollout of a fix here will be gated by https://mozilla-hub.atlassian.net/browse/DSRE-1639 to make sure we communicate the change.

**Comment by BenWu** [comment]
I just reran schema generator with change in #266 and it applied the pageload metadata correctly https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/dfdf2d88ca9ea03e616bf209ceb4527bda51946d
