### ISSUE TITLE
Transpile "pipeline family" schemas

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#52]
Moving to this repo since it's likely where implementation will occur. With
https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/372 merged we have access to bq sink schemas for raw, decoded, and error tables, which are meant to be transpiled as part of the MSG pipeline. These schemas differ from standard schemas in two ways:

1. It's my understanding that we should not merge the standard metadata (`metadata_merge`) into these schemas, as they are already complete.
2. These schemas don't map to a particular namespace; rather, they are for creating tables at the "pipeline family" level of ingestion infrastructure (e.g. telemetry, structured, stub_installer, tls_error_reports).

The latter detail is handled in the infrastructure repo where the pipeline families are actually defined. The tentative logic is [here](https://github.com/mozilla-services/cloudops-infra/commit/6bdb89fe8921fac88aec9027c19f3c88d32c7e16) for reading the schemas that are added to the generated-schemas branch by this application (previously they were hard-coded). Currently, we merge structured metadata into the schemas under "metadata" and then [drop the generated bq schemas specifically](https://github.com/mozilla/mozilla-schema-generator/blob/master/bin/schema_generator.sh#L91) (though it looks like we don't need to since they aren't in the allowlist).

(Aside: while testing this I noticed we're not treating the metadata namespace specially while creating BQ schemas, ergo:

    [2019-08-05 00:52:37,406] {logging_mixin.py:95} INFO - [2019-08-05 00:52:37,406] {pod_launcher.py:104} INFO - Merging metadata metadata/structured-ingestion/structured-ingestion.1.schema.json and schema ./metadata/structured-ingestion/structured-ingestion.1.schema.json

Presumably this is a no-op.)

I have a [tentative PR](https://github.com/mozilla/mozilla-schema-generator/pull/51) that:

1. Removes metadata merging from the metadata namespace
  a. A consequence of this is that there is an AWS metadata schema that is not transpilable without the metadata merge, so I added a special case to not process that schema
2. Adds the schemas we care about under metadata to the allowlist
3. Removes special removal of the metadata namespace

I think this more or less gets us what we want but it's a little bit weird and I'm open to other ways of handling this.

**Comment by fbertsch** [comment]
@whd can you explain more about this piece?

> These schemas don't map to a particular namespace; rather, they are for creating tables at the "pipeline family" level of ingestion infrastructure (e.g. telemetry, structured, stub_installer, tls_error_reports).

Does that mean that every namespace should have an associated table for e.g. `error`?

**Comment by whd** [comment]
> @whd can you explain more about this piece?
> 
> > These schemas don't map to a particular namespace; rather, they are for creating tables at the "pipeline family" level of ingestion infrastructure (e.g. telemetry, structured, stub_installer, tls_error_reports).
> 
> Does that mean that every namespace should have an associated table for e.g. `error`?

No, this means that we'll only have 4 error tables under a single dataset `payload_bytes_errors` (e.g. telemetry, structured, stub_installer, tls_error_reports). This is because data can fail validation against any of these streams before a namespace or other attributes can be properly decoded and we'll want to be able to route those.

I'm thinking however that we're going to want to create user-facing views per-namespace into these table to restrict access to some fields (in particular `x-forwarded-for`), which roughly maps to an errors table per namespace. In this configuration the `payload_bytes_errors` table has read access limited and each view would select on the uri to match to its namespace. The most interesting case here is the `firefox-installer` namespace, which is populated by two different pipeline families (stub_installer and structured). Being able to distinguish errors by pipeline family may be useful, and it's not obvious to me whether that can be done in a view without adding a column for pipeline family or having separate tables. I'm mostly concentrated on creating the errors tables themselves however and user-facing views can follow.

**Comment by jklukas** [comment]
I agree that we can figure out authorized views on top of these later on.

**Comment by whd** [comment]
via https://github.com/mozilla/mozilla-schema-generator/pull/51
