### ISSUE TITLE
Generate the saved-session ping schema

### ISSUE THREAD

**Issue by fbertsch** [mozilla/mozilla-schema-generator#53]
This should mirror the `main` ping, but with a different `docType`.

We could even consider simply copying the BQ schema file over if it is an exact match.

**Comment by jklukas** [comment]
I wonder if a soft link in the `templates/` directory would work to allow us to copy the main ping schema content and keep it in sync.

**Comment by acmiyaguchi** [comment]
https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/368 is also similar to this issue -- its also a `main` ping with a different document type.

**Comment by fbertsch** [comment]
@acmiyaguchi does it include all the same probes as the main ping?

**Comment by acmiyaguchi** [comment]
Yes, the implementation can be found in [bug 1390095](https://bugzilla.mozilla.org/show_bug.cgi?id=1390095). It's literally a copy of the first ping, which is generally only seen on the second startup.
