### ISSUE TITLE
Provided Schema does not match Table moz-fx-data-shar-nonprod-efed:org_mozilla_fenix_live.metrics_v1. Field metrics.counter is missing in new schema, invalid

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#67]
This appears to be unrelated to https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/366#issuecomment-518767118 which was the last known set of glean-ish schema issues (affecting bookmarks_sync and history_sync tables).

It's in the same commit as the one investigated in https://github.com/mozilla/mozilla-schema-generator/issues/62: https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/fbfee46a2d38478f3542ae22f12402d2627f8ec9#diff-fd2d149510059777ef4b67e01f213b69R219 but is likely unrelated and not fixed by #65.

**Comment by jklukas** [comment]
cc @fbertsch @acmiyaguchi

**Comment by acmiyaguchi** [comment]
The cause of the missing `metrics.counter` is opaque to me. It's hinted by @fbertsch in the data-eng-and-ops channel yesterday that the probe was removed from the [fenix probe dictionary](https://probeinfo.telemetry.mozilla.org/glean/fenix/metrics).

**Comment by whd** [comment]
Fixed by https://github.com/mozilla/mozilla-schema-generator/pull/68
