### ISSUE TITLE
Fields dropped from schemas in main ping

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#69]
https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/2db57aa3cfa96981fd7a4c281d4f37a0ecee9dab

**Comment by acmiyaguchi** [comment]
@whd The BQ schemas have been updated as per https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/b2a4a29d8a11896138a7bf3446eaf1d7102620a4.

**Comment by whd** [comment]
The schema update succeeded in stage, though it'll likely await the merging of https://github.com/mozilla/bigquery-etl/pull/318 to go out to prod.
