### ISSUE TITLE
Consider failing on invalid schema change

### ISSUE THREAD

**Issue by fbertsch** [mozilla/mozilla-schema-generator#74]
@whd this is basically a question for you. Would you like us to have the schema-generator fail on invalid schema changes, or continue having the current pipeline move to deploy and fail later?

**Comment by whd** [comment]
The current mechanism for addressing schema issues is:

1. The Jenkins job fails in stage and alerts me
2. I manually file an issue and point at the ref that causes the failure

The alerts in (1) happen in our stage environment which is also supposed to send an email telemetry-alerts@, but that needs to be fixed up and isn't working. 

For tracking purposes (2) is probably valuable even if we move schema validation into the probe-scraper dag. It is potentially useful to have artifacts and commits to reference when creating these issues, but the logs from the airflow job might be just as good or better for this purpose. Notably, (2) does not need to be done by me in the event that this change is implemented.

There are potentially cases where we want to deploy breaking schema changes i.e. to delete/recreate tables. These already require manual ops intervention to perform but in such cases we'll still want to be able to be able to update the MPS branch using our infrastructure and systems (i.e. not manually). We'd probably want some signal for cases like this, such as e.g. adding "[BREAKING]" to the MPS commits that are expected to have this issue.

On the whole I think adding validation pre-Jenkins is probably better for developer visibility and general workflow, assuming it is still easy to diagnose and fix schemas errors and that we can still commit breaking schema changes if/when necessary. It makes one small task that is currently ops responsibility the responsibility of the owner of probe-scraper dag, which is a good thing. I would consider this feature low priority.
