### ISSUE TITLE
`user_prefs` are not set to string for every ping

### ISSUE THREAD

**Issue by fbertsch** [mozilla/mozilla-schema-generator#78]
We wanted to set `user_prefs` to strings to ensure they are all available as schema elements. However that didn't occur with https://github.com/mozilla/mozilla-schema-generator/commit/9ffd4072138a0a042a805b94df744941b4b2731c, instead it only set them to strings for `main`, `saved-session`, and `first-shutdown`.

If we want to set it for all pings containing environment, we need to either:
- Add a script to edit all pings, ala metadata merge
- Have the schema-generator generate all pings, not just main variants and glean

**Comment by acmiyaguchi** [comment]
This was fixed in #120
