### ISSUE TITLE
Add scalar processing to the deletion-request ping

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/mozilla-schema-generator#85]
Per [Bug 1602064](https://bugzilla.mozilla.org/show_bug.cgi?id=1602064), the `deletion-request` ping will start reporting scalars. We should support that in the schema generator.

**Comment by mreid-moz** [comment]
@scholtzan There's a related bug @ https://bugzilla.mozilla.org/show_bug.cgi?id=1614416 - if it doesn't add too much work/scope, please consider tackling that one as part of this work.

**Comment by scholtzan** [comment]
Fixed in https://github.com/mozilla/mozilla-schema-generator/pull/120
