### ISSUE TITLE
deletion-request docType missing

### ISSUE THREAD

**Issue by mdboom** [mozilla/mozilla-schema-generator#88]
Looking at the Glean [schema rejection dashboard for Fenix nightly](
https://console.cloud.google.com/bigquery?sq=1018637472215:1745303b65874ef68114edc55854dfcc
):

There are maybe 100 instances of:

`com.mozilla.telemetry.schemas.SchemaNotFoundException: No such docType: org-mozilla-fenix-nightly/deletion-request`

**Comment by mdboom** [comment]
Cc: @fbertsch

**Comment by scholtzan** [comment]
Fixed in https://github.com/mozilla/mozilla-schema-generator/pull/82
