### ISSUE TITLE
Latest generated-schemas branch includes non-normalized namespaces

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#91]
[commit](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/8e3d4c28cbe88d01aa165d3227be0da96cf63720)

`org.mozilla.ios.Lockbox` `org.mozilla.fogotype` `mozilla.Lockbox` will all cause problems further down the pipeline as they [aren't valid namespaces](https://docs.telemetry.mozilla.org/cookbooks/new_ping.html#choose-a-namespace-and-doctype). Replacing `.` with `-` and lowercasing i.e. `org-mozilla-ios-lockbox`, `org-mozilla-fogotype`, `mozilla-lockbox` would match namespace requirements.

**Comment by fbertsch** [comment]
This is on me. Looks like I set the name where the app-id should be, and the app-id where the name should be.

**Comment by fbertsch** [comment]
Huh, no I did not. Investigating, this shouldn't be occurring.

**Comment by whd** [comment]
After today's push it looks like the only remaining issue is with [capitalization](https://github.com/mozilla-services/mozilla-pipeline-schemas/tree/generated-schemas/schemas/mozilla-Lockbox).
