### ISSUE TITLE
Field metrics.counter.events_total_uri_count is missing in new schema, invalid

### ISSUE THREAD

**Issue by whd** [mozilla/mozilla-schema-generator#96]
This affects the following tables:

google_bigquery_table.org_mozilla_fenix_metrics_v1_live
google_bigquery_table.org_mozilla_fenix_metrics_v1_stable
google_bigquery_table.org_mozilla_fenix_nightly_metrics_v1_live
google_bigquery_table.org_mozilla_fenix_nightly_metrics_v1_stable
google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_live
google_bigquery_table.org_mozilla_vrbrowser_session_end_v1_stable

This looks to be a result of [this commit](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/8e3d4c28cbe88d01aa165d3227be0da96cf63720) from three days ago. The last prod schemas deploy was on the 9th, a week ago.

**Comment by fbertsch** [comment]
This should be fixed by https://github.com/mozilla/probe-scraper/pull/165. Rerunning the probe-scraper now.

**Comment by fbertsch** [comment]
Looks like the schemas are back to normal: https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/71f74e619b65c407efd9f4f818b7abf80147b883
